deploymentName: users-api
namespace: app
autoscaling:
  enabled: true
replicaCount: 1
containerName: users-api
image:
  repository: harbor.1.2.3.4.nip.io/app/dashboardui
  tag: v1
  pullPolicy: IfNotPresent
service:
  port: 80
  name: users-api-service
configmapName: users-api-configmap
app_port: 3000
