deploymentName: documents-api
namespace: app
autoscaling:
  enabled: true
replicaCount: 1
containerName: documents-api
image:
  repository: harbor.1.2.3.4.nip.io/app/dashboardui
  tag: v1
  pullPolicy: IfNotPresent
service:
  port: 80
  name: documents-api-service
configmapName: documents-api-configmap
app:
  port: 3001
