ingress:
  name: app-ingress
  namespace: app
  host: 4.2.1.1.nip.io
  pathType: Prefix
  port: 80
frontendPath: /
backendUsersPath: /users
backendDocsPath: /documents
dashboardService: dashboard-ui-service
usersService: users-api-service
docsService: documents-api-service


autoscaling:
  enabled: true
replicaCount: 1
containerName: dashboard-ui
image:
  repository: harbor.1.2.3.4.nip.io/app/dashboardui
  tag: v1
  pullPolicy: IfNotPresent
service:
  port: 80
  name: dashboard-ui-service
configmapName: dashboard-ui-configmap
app:
  port: 3091
