ingress:
  name: app-ingress
  namespace: app
  host: 4.2.1.1.nip.io
  pathType: Prefix
  port: 80
frontendPath: /
backendUsersPath: /users
backendDocsPath: /documents
dashboardService: dashboard-ui-service
usersService: users-api-service
docsService: documents-api-service

