{{- define "chart-library.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.confimap_name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  {{ include "app-configmap.tpl" . | nindent 2 }}
{{- end -}}  