{{- define "chart-library.configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmapName }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  {{- include "app-configmap" . | nindent 2 }}
{{- end }}  