{{- define "chart-library.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "app-labels" . | nindent 4 }}
spec:
  {{- if .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "image-pull-secrets" . | nindent 6 }}
      containers:
      - name: {{ .Values.containerName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        {{- include "env-from-configmap" . | nindent 8 }}
        env:
        {{- include "env-from-secret" . | nindent 8 }}
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
          protocol: TCP
        livenessProbe:
          {{- include "liveness-probe" . | nindent 10 }}
{{- end }}